# server
server:
  port: 8055

# spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diet?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: noah_1324

# redis
redis:
  host: 127.0.0.1
  port: 6379

# token
token:
  login-url: "/users/login"
  ignore-paths:
    /users/register
